import type { Metadata } from "next";
import "./globals.css";
import ReactAriaProvider from "@/components/providers/react-aria-provider";

export const metadata: Metadata = {
  title: "PWA Messenger",
  description: "Generated by create next app & Developed by Saman-Safaei-Dev",
};

type Props = {
  children: React.ReactNode;
};

function RootLayout(props: Props) {
  const { children } = props;

  return (
    <html lang="en">
      <body className="antialiased">
        <ReactAriaProvider>{children}</ReactAriaProvider>
      </body>
    </html>
  );
}

export default RootLayout;
